project: 
  type: website
  output-dir: docs
  
website: 
  title: "My Portfolio"
  navbar: 
   left: 
    - text: "About me"
      href: aboutme.qmd
      url: "/Users/sriyapothula/Desktop/stat/mywebsite/IMG_7712.JPG"
    - text: "Education"
      href: education.qmd
    - text: "Work History"
      href: workhistory.qmd
    - text: "Skills"
      href: skills.qmd
format: 
 html: 
  theme: vapor
  