project: 
  type: website
  output-dir: docs
  
website: 
  title: "My Portfolio"
  navbar: 
   left: 
    - text: "About me"
      href: aboutme.qmd
    - text: "Education"
      href: education.qmd
    - text: "Work History"
      href: workhistory.qmd
    - text: "Skills"
      href: skills.qmd
    - text: "Projects"
      href: projects.qmd
format: 
 html: 
  theme: vapor
  