<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>My Portfolio - Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">My Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./aboutme.html" rel="" target="">
 <span class="menu-text">About me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./education.html" rel="" target="">
 <span class="menu-text">Education</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./workhistory.html" rel="" target="">
 <span class="menu-text">Work History</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./skills.html" rel="" target="">
 <span class="menu-text">Skills</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Final_Project.html" rel="" target="" aria-current="page">
 <span class="menu-text">Final Project</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Project</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><strong>Group 9</strong></p>
<section id="predicting-the-age-of-abalone-based-on-data-visualization-analysis" class="level1">
<h1>Predicting the Age of Abalone based on Data Visualization Analysis</h1>
<p>by</p>
<p><img src="images/clipboard-3215116520.png" class="img-fluid"></p>
<p>Darshini Balakrishnan</p>
<p>Sai Padma Sriya Pothula</p>
<p>Adhi Mohan</p>
<section id="abstract" class="level3">
<h3 class="anchored" data-anchor-id="abstract"><strong>Abstract:</strong></h3>
<p>The “Age Prediction of Abalone” in this project incorporates a new way to find out the Abalone Age. Abalone’s physical measurements are used to predict the Abalone Age by Random Forest method. This trained model gives us the age of the Abalone in just a few clicks instead of all the labor put into cutting the shell and counting the rings of Abalone, saving the production costs. The data is visualized for a better understanding.</p>
</section>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction"><strong>Introduction:</strong></h3>
<p>The abalone dataset encapsulates a collection of morphological measurements of abalone, a marine gastropod mollusk, used to predict its age through the number of rings on its shell. Regression models are used for predicting the biological ages based on physical data. The challenge lies in accurately modeling these predictions, which has significant implications for biological research and marine conservation efforts. Our analysis employs various statistical and machine learning techniques to enhance the precision of age prediction, providing insights into the factors most significantly influencing abalone’s aging process.</p>
<p>In this project, we delve into the abalone dataset to develop a robust model that can predict the age of abalone from its physical measurements with high accuracy. Our approach includes a thorough exploratory data analysis to identify patterns and anomalies, preprocessing steps to optimize the dataset for modeling, and the application of multiple regression techniques to compare their effectiveness. The outcome of this project is expected to contribute valuable insights to marine biology by improving the understanding of abalone’s growth factors and supporting the development of data-driven conservation policies.</p>
</section>
<section id="dataset" class="level3">
<h3 class="anchored" data-anchor-id="dataset"><strong>Dataset:</strong></h3>
<p>The dataset comes from&nbsp;<strong>a 1994 study “The Population Biology of Abalone (Haliotis&nbsp;species) in Tasmania</strong>. I. Blacklip Abalone (H. rubra) from the North Coast and Islands of Bass Strait”.</p>
<p>Abalone, marine snails found in various oceans, are studied not only for their ecological importance but also for their commercial value. The abalone dataset includes several biometric measurements such as length, diameter, height, whole weight, shucked weight, viscera weight, and shell weight, along with the number of rings, which directly correlates to age. This dataset is derived from a comprehensive study aimed at understanding the growth patterns and age distribution of abalone, which is crucial for sustainable harvesting and conservation strategies.</p>
<p>The dependent variable Rings is included in the dataset. It was measured as the number of rings observed after cutting and examining an abalone. Although it does not denote the age of a given abalone directly, it determines it more-or-less perfectly. The age of an abalone equals Rings + 1.5 . Since this relationship holds reliably, Rings will be considered as the dependent variable.</p>
<table class="table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td><strong>Row Number</strong></td>
<td></td>
<td><strong>Name</strong></td>
<td></td>
<td><strong>Data Type</strong></td>
<td></td>
<td><strong>Measurement Unit</strong></td>
<td></td>
<td><strong>Description</strong></td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>1.</td>
<td></td>
<td>Sex</td>
<td></td>
<td>Nominal</td>
<td></td>
<td>NA</td>
<td></td>
<td>Male(M), Female(F) and Infant(F)</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>2.</td>
<td></td>
<td>Length</td>
<td></td>
<td>Continuous</td>
<td></td>
<td>mm</td>
<td></td>
<td>Longest Shell measurement</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>3.</td>
<td></td>
<td>Diameter</td>
<td></td>
<td>Continuous</td>
<td></td>
<td>mm</td>
<td></td>
<td>Perpendicular to length</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>4.</td>
<td></td>
<td>Height</td>
<td></td>
<td>Continuous</td>
<td></td>
<td>mm</td>
<td></td>
<td>Measured with meat in the shell</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>5.</td>
<td></td>
<td>Whole weight</td>
<td></td>
<td>Continuous</td>
<td></td>
<td>gm</td>
<td></td>
<td>Whole Abalone weight</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>6.</td>
<td></td>
<td>Shucked weight</td>
<td></td>
<td>Continuous</td>
<td></td>
<td>gm</td>
<td></td>
<td>Weight of meat</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>7.</td>
<td></td>
<td>Viscera weight</td>
<td></td>
<td>Continuous</td>
<td></td>
<td>gm</td>
<td></td>
<td>Gut weight(after bleeding)</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>8.</td>
<td></td>
<td>Shell weight</td>
<td></td>
<td>Continuous</td>
<td></td>
<td>gm</td>
<td></td>
<td>After being dried</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>9.</td>
<td></td>
<td>Rings</td>
<td></td>
<td>Integer</td>
<td></td>
<td>NA</td>
<td></td>
<td>+1.5 gives the age in years</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="methodology" class="level3">
<h3 class="anchored" data-anchor-id="methodology">Methodology:</h3>
<p>The first step is to Read the data from the csv file, where we need to check for any missing values. We use the ‘sum’ function to determine if there are any missing values and for the completeness of the data.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>abalone <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"/Users/sriyapothula/Desktop/stat/Abalone/abalone.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(abalone))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">complete.cases</span>(abalone))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4177</code></pre>
</div>
</div>
<p>The above result indicated that the Abalone dataset is a complete dataset.</p>
</section>
<section id="predicting-the-age-of-abalone" class="level2">
<h2 class="anchored" data-anchor-id="predicting-the-age-of-abalone">Predicting the Age of Abalone:</h2>
<p>Let us start with relationship between features ( correlation coefficient matrix) and the relationship between the visual features. The objective of the data visualization step in our research is to conduct a comprehensive exploratory data analysis (EDA) to understand the relationships between various physical measurements of abalones and their sex classification (Female, Male, Infant). The visualization aims to uncover underlying patterns, associations, and distributions within the dataset, which are crucial for informing subsequent data processing and predictive modeling stages.</p>
<p>We employ the <strong><code>GGally</code></strong> package in R, specifically the <strong><code>ggpairs</code></strong> function, to generate a pairs plot. This function is highly effective for visualizing pairwise relationships and distributions across multiple dimensions of a dataset.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(abalone, <span class="fu">aes</span>(<span class="at">colour =</span> Sex, <span class="at">alpha =</span> <span class="fl">0.8</span>), <span class="at">title=</span><span class="st">"Pairs plot for abalone dataset"</span>) <span class="sc">+</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_grey</span>(<span class="at">base_size =</span> <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the above plots, Variables such as Length, Diameter, and Whole_weight show strong positive correlations with each other across all sex categories. This is expected as larger abalones generally have greater dimensions and weights. Length diameter and height have similar distributions across sexes but with slight variations in median and variability, particularly between infants and adults. Whole weight and Shucked weight Show significant differences among the sexes, suggesting that these features are good discriminators for sex classification.</p>
<p>The presence of “***” next to a correlation value suggests a very strong statistical significance for that correlation.</p>
</section>
<section id="data-visualization-and-statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-visualization-and-statistical-analysis"><strong>Data Visualization and Statistical Analysis</strong></h2>
<p>In the initial phase of our study, we employ <strong><code>ggplot2</code></strong> from the <strong><code>tidyverse</code></strong> package to create visual representations of the abalone dataset. A histogram details the distribution of the ‘Rings’ variable, which serves as a proxy for age, while a boxplot is used to compare this distribution across different sex categories, providing insights into central tendencies and variability. Additionally, a pairs plot generated using the base R function <strong><code>pairs</code></strong> visually assesses the relationships among key continuous variables such as Length, Diameter, Height, and Whole_weight. This visualization is instrumental in identifying correlations and potential multicollinearity among predictors. Furthermore, an Analysis of Variance (ANOVA) tests for significant differences in the mean number of rings across sex groups, helping determine if sex significantly influences abalone age.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>randomForest 4.7-1.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Type rfNews() to see new features/changes/bug fixes.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'randomForest'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    margin</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lattice</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'caret'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    lift</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>corrplot 0.92 loaded</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(abalone, <span class="fu">aes</span>(<span class="at">x =</span> Rings)) <span class="sc">+</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Rings"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation"><strong>Interpretation:</strong></h3>
<p>The histogram shows a unimodal distribution with a strong peak around 9 to 10 rings, suggesting that the majority of abalones in the dataset are around 9 to 10 years old. The distribution is slightly right-skewed, indicating a tail of older abalones with more rings. Few abalones have very high ring counts, as seen from the declining frequency past 15 rings, which is typical for biological data where fewer individuals reach older ages. This visualization provides a clear view of the age structure within the abalone population studied, which is crucial for biological and ecological analysis, potentially guiding conservation and harvesting strategies.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(abalone, <span class="fu">aes</span>(<span class="at">x =</span> Sex, <span class="at">y =</span> Rings)) <span class="sc">+</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"cyan"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Rings Distribution by Sex"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(<span class="sc">~</span>Length <span class="sc">+</span> Diameter <span class="sc">+</span> Height <span class="sc">+</span> Whole_weight, <span class="at">data =</span> abalone, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">"Pairwise Relationships"</span>, <span class="at">pch =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1"><strong>Interpretation:</strong></h3>
<p>The “Pairwise Relationships” plot displays the correlation between several physical measurements of abalones: Length, Diameter, Height, and Whole_weight. Each plot demonstrates a positive correlation among these variables, particularly between Length and Diameter, and Length and Whole_weight, which show strong linear relationships. This indicates that as abalones grow longer, they also tend to increase proportionally in diameter and overall weight. The relationship between Height and the other variables, while still positive, appears weaker and more dispersed, suggesting that height may vary more independently compared to length or diameter. Overall, these relationships are expected in biological organisms, where physical dimensions often scale together, but the varying degrees of correlation may also hint at different growth patterns or environmental adaptations specific to the species.</p>
<p>Furthermore, an Analysis of Variance (ANOVA) tests for significant differences in the mean number of rings across sex groups, helping determine if sex significantly influences abalone age.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(Rings <span class="sc">~</span> Sex, <span class="at">data =</span> abalone)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value Pr(&gt;F)    
Sex            2   8381    4191   499.3 &lt;2e-16 ***
Residuals   4174  35030       8                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="interpretation-2" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-2"><strong>Interpretation:</strong></h3>
<p>The output from the ANOVA (Analysis of Variance) test indicates a significant effect of the variable ‘Sex’ on the number of rings in abalones, which are used as a proxy for age. With a very high F-value of 499.3 and an extremely low p-value (less than 2e-16), we reject the null hypothesis that there are no differences in mean number of rings across the sex categories of abalones. This suggests that the average number of rings, and hence the age distribution, differs statistically significantly between the sexes. The degrees of freedom for the ‘Sex’ group is 2, reflecting the three levels compared (female, male, and infant), and the residuals have 4174 degrees of freedom, indicating the sample size minus the number of groups. This strong statistical evidence supports that sex is a significant factor influencing the age as measured by rings in abalones.</p>
</section>
<section id="correlation-analysis-and-machine-learning-modeling" class="level3">
<h3 class="anchored" data-anchor-id="correlation-analysis-and-machine-learning-modeling"><strong>Correlation Analysis and Machine Learning Modeling:</strong></h3>
<p>Correlation analysis is conducted using the <strong><code>cor</code></strong> function to establish a correlation matrix for numerical variables, quantifying the degree of linear relationships between them. This analysis aids in feature selection and informs subsequent modeling strategies. The study progresses by employing machine learning techniques where a Random Forest model is trained using the <strong><code>randomForest</code></strong> package to ascertain variable importance, which guides the refinement of our predictive models. Subsequent models, including Support Vector Machines (SVM), Gradient Boosting Machines (GBM), and Linear Regression, are trained and compared using the <strong><code>caret</code></strong> package to evaluate their performance based on Root Mean Square Error (RMSE) and R^2 metrics. These steps encapsulate our approach to harnessing advanced analytics to predict the age of abalones more accurately, enhancing our understanding of this species’ growth patterns.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>Sex <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(abalone<span class="sc">$</span>Sex)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>correlations <span class="ot">&lt;-</span> <span class="fu">cor</span>(abalone[,<span class="sc">-</span><span class="dv">1</span>])</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>correlations</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                  Length  Diameter    Height Whole_weight Shucked_weight
Length         1.0000000 0.9868116 0.8275536    0.9252612      0.8979137
Diameter       0.9868116 1.0000000 0.8336837    0.9254521      0.8931625
Height         0.8275536 0.8336837 1.0000000    0.8192208      0.7749723
Whole_weight   0.9252612 0.9254521 0.8192208    1.0000000      0.9694055
Shucked_weight 0.8979137 0.8931625 0.7749723    0.9694055      1.0000000
Viscera_weight 0.9030177 0.8997244 0.7983193    0.9663751      0.9319613
Shell_weight   0.8977056 0.9053298 0.8173380    0.9553554      0.8826171
Rings          0.5567196 0.5746599 0.5574673    0.5403897      0.4208837
               Viscera_weight Shell_weight     Rings
Length              0.9030177    0.8977056 0.5567196
Diameter            0.8997244    0.9053298 0.5746599
Height              0.7983193    0.8173380 0.5574673
Whole_weight        0.9663751    0.9553554 0.5403897
Shucked_weight      0.9319613    0.8826171 0.4208837
Viscera_weight      1.0000000    0.9076563 0.5038192
Shell_weight        0.9076563    1.0000000 0.6275740
Rings               0.5038192    0.6275740 1.0000000</code></pre>
</div>
</div>
</section>
<section id="interpretation-3" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-3"><strong>Interpretation:</strong></h3>
<p>The variable importance plots from a random forest model reveal key predictors for estimating the age of abalones, measured by the number of rings. In the left plot, which shows percentage increase in mean squared error (%IncMSE), ‘Shucked_weight’ emerges as the most critical predictor, followed by ‘Sex’ and ‘Shell_weight’, indicating that model accuracy heavily relies on these variables. The right plot, displaying increase in node purity (IncNodePurity), also highlights ‘Shell_weight’ as the top variable, with ‘Whole_weight’ and ‘Shucked_weight’ also showing significant influence. These metrics suggest that factors related to the physical composition of abalones, particularly the weights of different body parts, along with the sex, play crucial roles in accurately determining their age, with these variables significantly affecting the model’s predictive accuracy and ability to create homogeneous groups.</p>
</section>
<section id="implementing-different-models" class="level3">
<h3 class="anchored" data-anchor-id="implementing-different-models"><strong>Implementing different models:</strong></h3>
<p>The dataset is split into training and testing sets, 80-20 respectively. The training control is prepared for 10-fold cross-validation, a technique that improves the reliability of model evaluation by training and testing the models on ten distinct data subsets.</p>
<p><strong>Random Forest:</strong> A regression model utilizing random forests is trained. Multiple decision trees are used in this ensemble model to reduce overfitting and increase prediction accuracy.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Rings <span class="sc">~</span> ., <span class="at">data =</span> abalone, <span class="at">importance =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">varImpPlot</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>abalone_no_sex <span class="ot">&lt;-</span> abalone[, <span class="sc">!</span><span class="fu">names</span>(abalone) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sex"</span>)]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>index <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(abalone_no_sex<span class="sc">$</span>Rings, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">TRUE</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> abalone_no_sex[index<span class="sc">$</span>Resample1,]</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> abalone_no_sex[<span class="sc">-</span>index<span class="sc">$</span>Resample1,]</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>train_control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"cv"</span>, </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">number =</span> <span class="dv">10</span>   </span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>models <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>models<span class="sc">$</span>rf <span class="ot">&lt;-</span> <span class="fu">train</span>(Rings <span class="sc">~</span> ., <span class="at">data =</span> abalone_no_sex, <span class="at">method =</span> <span class="st">"rf"</span>, <span class="at">trControl =</span> train_control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Support Vector Machine (SVM):</strong> Data scaling is used to standardize feature scales after an SVM model with a radial basis function kernel has been trained.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>models<span class="sc">$</span>svm <span class="ot">&lt;-</span> <span class="fu">train</span>(Rings <span class="sc">~</span> ., <span class="at">data =</span> abalone_no_sex, <span class="at">method =</span> <span class="st">"svmRadial"</span>, <span class="at">trControl =</span> train_control, <span class="at">preProcess =</span> <span class="st">"scale"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Gradient Boosting Machine (GBM):</strong> After training, a GBM model creates trees one at a time, with each new tree aiding in the correction of mistakes produced by trees that have already been trained.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GBM</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>models<span class="sc">$</span>gbm <span class="ot">&lt;-</span> <span class="fu">train</span>(Rings <span class="sc">~</span> ., <span class="at">data =</span> abalone_no_sex, <span class="at">method =</span> <span class="st">"gbm"</span>, <span class="at">trControl =</span> train_control, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Linear Regression:</strong> Linear regression model is trained, which is useful as a baseline to assess the performance of more complex models.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Regression</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>models<span class="sc">$</span>lm <span class="ot">&lt;-</span> <span class="fu">train</span>(Rings <span class="sc">~</span> ., <span class="at">data =</span> abalone_no_sex, <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">trControl =</span> train_control)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>predictions_rf <span class="ot">&lt;-</span> <span class="fu">predict</span>(models<span class="sc">$</span>rf, test_data)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>predictions_svm <span class="ot">&lt;-</span> <span class="fu">predict</span>(models<span class="sc">$</span>svm, test_data)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>predictions_gbm <span class="ot">&lt;-</span> <span class="fu">predict</span>(models<span class="sc">$</span>gbm, test_data)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>predictions_lm <span class="ot">&lt;-</span> <span class="fu">predict</span>(models<span class="sc">$</span>lm, test_data)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>rmse_rf <span class="ot">&lt;-</span> <span class="fu">RMSE</span>(predictions_rf, test_data<span class="sc">$</span>Rings)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>r2_rf <span class="ot">&lt;-</span> <span class="fu">R2</span>(predictions_rf, test_data<span class="sc">$</span>Rings)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>rmse_svm <span class="ot">&lt;-</span> <span class="fu">RMSE</span>(predictions_svm, test_data<span class="sc">$</span>Rings)</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>r2_svm <span class="ot">&lt;-</span> <span class="fu">R2</span>(predictions_svm, test_data<span class="sc">$</span>Rings)</span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>rmse_gbm <span class="ot">&lt;-</span> <span class="fu">RMSE</span>(predictions_gbm, test_data<span class="sc">$</span>Rings)</span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>r2_gbm <span class="ot">&lt;-</span> <span class="fu">R2</span>(predictions_gbm, test_data<span class="sc">$</span>Rings)</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>rmse_lm <span class="ot">&lt;-</span> <span class="fu">RMSE</span>(predictions_lm, test_data<span class="sc">$</span>Rings)</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>r2_lm <span class="ot">&lt;-</span> <span class="fu">R2</span>(predictions_lm, test_data<span class="sc">$</span>Rings)</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"RF RMSE:"</span>, rmse_rf, <span class="st">"R2:"</span>, r2_rf, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>RF RMSE: 0.974506 R2: 0.9249036 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"SVM RMSE:"</span>, rmse_svm, <span class="st">"R2:"</span>, r2_svm, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>SVM RMSE: 1.969508 R2: 0.6417577 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"GBM RMSE:"</span>, rmse_gbm, <span class="st">"R2:"</span>, r2_gbm, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>GBM RMSE: 1.893171 R2: 0.6613736 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"LM RMSE:"</span>, rmse_lm, <span class="st">"R2:"</span>, r2_lm, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>LM RMSE: 2.125251 R2: 0.5691083 </code></pre>
</div>
</div>
<p>Random Forest shows the best performance among all models tested, with the lowest RMSE and highest R². This suggests it is most effective at capturing the variance in the data and making accurate predictions about the age of abalones.Based on the measurements, the Random Forest model is the clear winner and the best option for this specific forecasting task. Its low RMSE shows that its predictions are near to real values, and its strong R² value suggests that it can explain a considerable percentage of the variance in the age of abalones.</p>
</section>
<section id="setting-up-training-control" class="level3">
<h3 class="anchored" data-anchor-id="setting-up-training-control"><strong>Setting up Training control:</strong></h3>
<p>This methodically investigate several parameter choices to get the optimal option that reduces the root mean square error (RMSE) while estimating the number of rings in abalones. In addition to trying to increase accuracy, the model tuning makes sure the model performs well when applied to previously unknown data by employing a grid search with cross-validation. This methodical technique aids in choosing the best model settings to successfully improve predictive performance.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>train_control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>, <span class="at">search =</span> <span class="st">"grid"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>tune_grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">mtry =</span> <span class="fu">seq</span>(<span class="dv">2</span>, <span class="fu">ncol</span>(abalone_no_sex) <span class="sc">-</span> <span class="dv">1</span>, <span class="at">by =</span> <span class="dv">1</span>), </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">splitrule =</span> <span class="fu">c</span>(<span class="st">"variance"</span>),</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">min.node.size =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">10</span>)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>tuned_model <span class="ot">&lt;-</span> <span class="fu">train</span>(Rings <span class="sc">~</span> ., <span class="at">data =</span> abalone_no_sex, <span class="at">method =</span> <span class="st">"ranger"</span>,</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>                     <span class="at">trControl =</span> train_control, <span class="at">tuneGrid =</span> tune_grid,</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>                     <span class="at">metric =</span> <span class="st">"RMSE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="implementing-principal-component-analysis" class="level3">
<h3 class="anchored" data-anchor-id="implementing-principal-component-analysis"><strong>Implementing Principal Component Analysis:</strong></h3>
<p>By using PCA, you reduce noise and computational load, potentially improving the models’ performances. Training multiple models allows for a comparative analysis to determine which model best handles the PCA-transformed data in predicting abalone age.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(FactoMineR)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co">#abalone_no_sex =abalone[, !names(abalone) %in% c("Sex")]</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>abalone_pca <span class="ot">=</span> abalone_no_sex[, <span class="sc">!</span><span class="fu">names</span>(abalone) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Rings"</span>)]</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>data <span class="ot">=</span> abalone_pca  </span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>data_scaled <span class="ot">=</span> <span class="fu">scale</span>(data)</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>pca_result <span class="ot">=</span> <span class="fu">PCA</span>(data_scaled, <span class="at">graph =</span> <span class="cn">FALSE</span>)</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>num_components <span class="ot">=</span> <span class="fu">which</span>(<span class="fu">cumsum</span>(pca_result<span class="sc">$</span>eig[,<span class="dv">2</span>]) <span class="sc">&gt;</span> <span class="dv">85</span>)[<span class="dv">1</span>]</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>data_pca <span class="ot">=</span> pca_result<span class="sc">$</span>ind<span class="sc">$</span>coord[, <span class="dv">1</span><span class="sc">:</span>num_components]</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>num_components <span class="ot">=</span> <span class="fu">which</span>(<span class="fu">cumsum</span>(pca_result<span class="sc">$</span>eig[,<span class="dv">2</span>]) <span class="sc">&gt;</span> <span class="dv">85</span>)[<span class="dv">1</span>]</span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>data_pca <span class="ot">=</span> pca_result<span class="sc">$</span>ind<span class="sc">$</span>coord[, <span class="dv">1</span><span class="sc">:</span>num_components]</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>final_data <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">Rings =</span> abalone_pca<span class="sc">$</span>Rings, data_pca)</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a>index <span class="ot">=</span> <span class="fu">createDataPartition</span>(final_data<span class="sc">$</span>Rings, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">TRUE</span>)</span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>train_data_pca <span class="ot">=</span> final_data[index<span class="sc">$</span>Resample1,]</span>
<span id="cb44-23"><a href="#cb44-23" aria-hidden="true" tabindex="-1"></a>test_data_pca <span class="ot">=</span> final_data[<span class="sc">-</span>index<span class="sc">$</span>Resample1,]</span>
<span id="cb44-24"><a href="#cb44-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-25"><a href="#cb44-25" aria-hidden="true" tabindex="-1"></a>train_control_pca <span class="ot">=</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb44-26"><a href="#cb44-26" aria-hidden="true" tabindex="-1"></a>models_pca <span class="ot">=</span> <span class="fu">list</span>()</span>
<span id="cb44-27"><a href="#cb44-27" aria-hidden="true" tabindex="-1"></a>models_pca<span class="sc">$</span>rf <span class="ot">=</span> <span class="fu">train</span>(Rings <span class="sc">~</span> ., <span class="at">data =</span> train_data_pca, <span class="at">method =</span> <span class="st">"rf"</span>, <span class="at">trControl =</span> train_control_pca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>note: only 1 unique complexity parameters in default grid. Truncating the grid to 1 .</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>models_pca<span class="sc">$</span>svm <span class="ot">=</span> <span class="fu">train</span>(Rings <span class="sc">~</span> ., <span class="at">data =</span> train_data_pca, <span class="at">method =</span> <span class="st">"svmRadial"</span>, <span class="at">trControl =</span> train_control_pca)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>models_pca<span class="sc">$</span>gbm <span class="ot">=</span> <span class="fu">train</span>(Rings <span class="sc">~</span> ., <span class="at">data =</span> train_data_pca, <span class="at">method =</span> <span class="st">"gbm"</span>, <span class="at">trControl =</span> train_control_pca, <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Linear Regression</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>models_pca<span class="sc">$</span>lm <span class="ot">&lt;-</span> <span class="fu">train</span>(Rings <span class="sc">~</span> ., <span class="at">data =</span> train_data_pca, <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">trControl =</span> train_control_pca)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>predictions_rf_pca <span class="ot">=</span> <span class="fu">predict</span>(models_pca<span class="sc">$</span>rf, test_data_pca)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>predictions_svm_pca <span class="ot">=</span> <span class="fu">predict</span>(models_pca<span class="sc">$</span>svm, test_data_pca)</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>predictions_gbm_pca <span class="ot">=</span> <span class="fu">predict</span>(models_pca<span class="sc">$</span>gbm, test_data_pca)</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>predictions_lm_pca <span class="ot">=</span> <span class="fu">predict</span>(models_pca<span class="sc">$</span>lm, test_data_pca)</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>rmse_rf_pca <span class="ot">=</span> <span class="fu">RMSE</span>(predictions_rf_pca, test_data_pca<span class="sc">$</span>Rings)</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>r2_rf_pca <span class="ot">=</span> <span class="fu">R2</span>(predictions_rf_pca, test_data_pca<span class="sc">$</span>Rings)</span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>rmse_svm_pca <span class="ot">=</span> <span class="fu">RMSE</span>(predictions_svm_pca, test_data_pca<span class="sc">$</span>Rings)</span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>r2_svm_pca <span class="ot">=</span> <span class="fu">R2</span>(predictions_svm_pca, test_data_pca<span class="sc">$</span>Rings)</span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a>rmse_gbm_pca <span class="ot">=</span> <span class="fu">RMSE</span>(predictions_gbm_pca, test_data_pca<span class="sc">$</span>Rings)</span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a>r2_gbm_pca <span class="ot">=</span> <span class="fu">R2</span>(predictions_gbm_pca, test_data_pca<span class="sc">$</span>Rings)</span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a>rmse_lm_pca <span class="ot">=</span> <span class="fu">RMSE</span>(predictions_lm_pca, test_data_pca<span class="sc">$</span>Rings)</span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a>r2_lm_pca <span class="ot">=</span> <span class="fu">R2</span>(predictions_lm_pca, test_data_pca<span class="sc">$</span>Rings)</span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-24"><a href="#cb46-24" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"RF RMSE:"</span>, rmse_rf_pca, <span class="st">"R2:"</span>, r2_rf_pca, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>RF RMSE: 0.4754979 R2: 0.9781475 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"SVM RMSE:"</span>, rmse_svm_pca, <span class="st">"R2:"</span>, r2_svm_pca, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>SVM RMSE: 0.7983523 R2: 0.9387943 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"GBM RMSE:"</span>, rmse_gbm_pca, <span class="st">"R2:"</span>, r2_gbm_pca, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>GBM RMSE: 0.5245579 R2: 0.9734159 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"LM RMSE:"</span>, rmse_lm_pca, <span class="st">"R2:"</span>, r2_lm_pca, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>LM RMSE: 0.5061476 R2: 0.9754974 </code></pre>
</div>
</div>
<p>On this changed dataset, Random Forest is clearly the best performer, but Linear Regression also demonstrates excellent performance. By separating the most important characteristics and minimizing noise and duplication in the data, the application of PCA prior to model training has probably improved performance. In practical settings, these models—Random Forest and Linear Regression in particular—would be very useful for age prediction based on physical attributes, such as in biological research or abalone resource management.</p>
</section>
<section id="implementation-of-the-random-forest-model-in-shiny" class="level3">
<h3 class="anchored" data-anchor-id="implementation-of-the-random-forest-model-in-shiny"><strong>Implementation of the Random Forest model in Shiny:</strong></h3>
<p><em>#Shiny</em></p>
</section>
<section id="classification-and-prediction-of-maturity-of-abalone" class="level3">
<h3 class="anchored" data-anchor-id="classification-and-prediction-of-maturity-of-abalone"><strong>Classification and Prediction of Maturity of Abalone:</strong></h3>
<p>Abalones are classified into Mature and Immature based on the count of their Rings. It involves determining whether the abalone has reached a biological threshold that marks it as mature or immature. This method relies on analyzing the ring count, which correlates with age, as each ring generally signifies one year of growth.<br>
<br>
Using the training data as a Logistic Regression model, all other variables are used by the model to forecast the ‘Mature’ status; however, ‘Rings’ is specifically left out since ‘Mature’ is derived directly from it. The dependent variable (logistic regression) is binary, according to the binomial family specification. With logistic regression, data is fitted to a logistic curve to determine the likelihood that an event will occur. The values it gives, which range from 0 to 1, are understood as the likelihood that a certain observation falls into the category designated as “1.” This makes it perfect for situations when you want to determine the likelihood of an outcome in addition to predicting a binary outcome.Since the maturity status is a binary variable, logistic regression is the obvious choice.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)  </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Type 'citation("pROC")' for a citation.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'pROC'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    cov, smooth, var</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>Mature <span class="ot">&lt;-</span> <span class="fu">if_else</span>(abalone<span class="sc">$</span>Rings <span class="sc">&gt;=</span> <span class="dv">10</span>, <span class="st">"mature"</span>, <span class="st">"immature"</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>Sex <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(abalone<span class="sc">$</span>Sex)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>index <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(abalone<span class="sc">$</span>Mature, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">TRUE</span>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> abalone[index[[<span class="dv">1</span>]], ]</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> abalone[<span class="sc">-</span>index[[<span class="dv">1</span>]], ]</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>train_data<span class="sc">$</span>Mature <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(train_data<span class="sc">$</span>Mature <span class="sc">==</span> <span class="st">"mature"</span>)</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>model_log <span class="ot">&lt;-</span> <span class="fu">glm</span>(Mature <span class="sc">~</span> . <span class="sc">-</span>Rings, <span class="at">data =</span> train_data, <span class="at">family =</span> <span class="fu">binomial</span>())</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>predictions_log <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_log, test_data, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>predicted_classes_log <span class="ot">&lt;-</span> <span class="fu">if_else</span>(predictions_log <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">"mature"</span>, <span class="st">"immature"</span>)</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>predicted_classes_log <span class="ot">&lt;-</span> <span class="fu">factor</span>(predicted_classes_log, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"immature"</span>, <span class="st">"mature"</span>))</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>test_data<span class="sc">$</span>Mature <span class="ot">&lt;-</span> <span class="fu">factor</span>(test_data<span class="sc">$</span>Mature, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"immature"</span>, <span class="st">"mature"</span>))</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>confusion_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(predicted_classes_log, test_data<span class="sc">$</span>Mature)</span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>roc_curve <span class="ot">&lt;-</span> <span class="fu">roc</span>(test_data<span class="sc">$</span>Mature, predictions_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = immature, case = mature</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(roc_curve, <span class="at">main =</span> <span class="st">"ROC Curve for Logistic Regression"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="interpretation-4" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-4"><strong>Interpretation:</strong></h3>
<p>The ROC (Receiver Operating Characteristic) curve shown for the logistic regression model used to predict the maturity of abalones based on their ring counts provides a visual assessment of the model’s diagnostic ability. The ROC curve plots the true positive rate (sensitivity) against the false positive rate (1 - specificity) across a range of decision thresholds. A curve that approaches the top left corner of the plot indicates a high level of sensitivity and specificity, demonstrating an excellent predictive performance. In this graph, the curve significantly deviates from the diagonal line, which represents a random guess, suggesting that the logistic regression model has a strong ability to distinguish between mature and immature abalones. The area under the curve (AUC), while not explicitly stated, appears to be substantially higher than 0.5 (the AUC of a random classifier), confirming the effectiveness of the model.</p>
</section>
<section id="predictive-accuracy-of-abalone-age-between-different-sex-categories" class="level3">
<h3 class="anchored" data-anchor-id="predictive-accuracy-of-abalone-age-between-different-sex-categories"><strong>Predictive Accuracy of Abalone Age between different Sex categories:</strong></h3>
<p>The dataset is divided into 3 distinct subsets - Male, Female and Infant. Here, we are creating DataPartition() and each subset is further split into Training and Testing sets. Following this, Random Forest models are constructed independently for every Sex category, with the Sex. varibale being eliminated as a predictor. The <strong><code>glimpse(abalone)</code></strong> function call is likely used for a quick overview of the abalone dataset to understand its structure and variables.</p>
<p>The performance metrics for each model are printed, showing the RMSE and R² values for males, females, and infants. These metrics help in comparing the accuracy and explanatory power of the models across different sex categories, highlighting potential differences in prediction reliability and effectiveness.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(abalone)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,177
Columns: 10
$ Sex            &lt;fct&gt; M, M, F, M, I, I, F, F, M, F, F, M, M, F, F, M, I, F, M…
$ Length         &lt;dbl&gt; 0.455, 0.350, 0.530, 0.440, 0.330, 0.425, 0.530, 0.545,…
$ Diameter       &lt;dbl&gt; 0.365, 0.265, 0.420, 0.365, 0.255, 0.300, 0.415, 0.425,…
$ Height         &lt;dbl&gt; 0.095, 0.090, 0.135, 0.125, 0.080, 0.095, 0.150, 0.125,…
$ Whole_weight   &lt;dbl&gt; 0.5140, 0.2255, 0.6770, 0.5160, 0.2050, 0.3515, 0.7775,…
$ Shucked_weight &lt;dbl&gt; 0.2245, 0.0995, 0.2565, 0.2155, 0.0895, 0.1410, 0.2370,…
$ Viscera_weight &lt;dbl&gt; 0.1010, 0.0485, 0.1415, 0.1140, 0.0395, 0.0775, 0.1415,…
$ Shell_weight   &lt;dbl&gt; 0.150, 0.070, 0.210, 0.155, 0.055, 0.120, 0.330, 0.260,…
$ Rings          &lt;int&gt; 15, 7, 9, 10, 7, 8, 20, 16, 9, 19, 14, 10, 11, 10, 10, …
$ Mature         &lt;chr&gt; "mature", "immature", "immature", "mature", "immature",…</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>abalone_m <span class="ot">&lt;-</span> abalone <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">'M'</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>abalone_f <span class="ot">&lt;-</span> abalone <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">'F'</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>abalone_i <span class="ot">&lt;-</span> abalone <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sex <span class="sc">==</span> <span class="st">'I'</span>)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  </span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>trainIndex_m <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(abalone_m<span class="sc">$</span>Rings, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>train_m <span class="ot">&lt;-</span> abalone_m[trainIndex_m, ]</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>test_m <span class="ot">&lt;-</span> abalone_m[<span class="sc">-</span>trainIndex_m, ]</span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a>trainIndex_f <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(abalone_f<span class="sc">$</span>Rings, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a>train_f <span class="ot">&lt;-</span> abalone_f[trainIndex_f, ]</span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a>test_f <span class="ot">&lt;-</span> abalone_f[<span class="sc">-</span>trainIndex_f, ]</span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a>trainIndex_i <span class="ot">&lt;-</span> <span class="fu">createDataPartition</span>(abalone_i<span class="sc">$</span>Rings, <span class="at">p =</span> <span class="fl">0.8</span>, <span class="at">list =</span> <span class="cn">FALSE</span>)</span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a>train_i <span class="ot">&lt;-</span> abalone_i[trainIndex_i, ]</span>
<span id="cb64-18"><a href="#cb64-18" aria-hidden="true" tabindex="-1"></a>test_i <span class="ot">&lt;-</span> abalone_i[<span class="sc">-</span>trainIndex_i, ]</span>
<span id="cb64-19"><a href="#cb64-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-20"><a href="#cb64-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-21"><a href="#cb64-21" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span>
<span id="cb64-22"><a href="#cb64-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-23"><a href="#cb64-23" aria-hidden="true" tabindex="-1"></a>model_m <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Rings <span class="sc">~</span> . <span class="sc">-</span>Sex, <span class="at">data =</span> train_m)</span>
<span id="cb64-24"><a href="#cb64-24" aria-hidden="true" tabindex="-1"></a>model_f <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Rings <span class="sc">~</span> . <span class="sc">-</span>Sex, <span class="at">data =</span> train_f)</span>
<span id="cb64-25"><a href="#cb64-25" aria-hidden="true" tabindex="-1"></a>model_i <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(Rings <span class="sc">~</span> . <span class="sc">-</span>Sex, <span class="at">data =</span> train_i)</span>
<span id="cb64-26"><a href="#cb64-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-27"><a href="#cb64-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-28"><a href="#cb64-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-29"><a href="#cb64-29" aria-hidden="true" tabindex="-1"></a>predictions_m <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_m, test_m)</span>
<span id="cb64-30"><a href="#cb64-30" aria-hidden="true" tabindex="-1"></a>rmse_m <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((predictions_m <span class="sc">-</span> test_m<span class="sc">$</span>Rings)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb64-31"><a href="#cb64-31" aria-hidden="true" tabindex="-1"></a>r2_m <span class="ot">&lt;-</span> <span class="fu">cor</span>(predictions_m, test_m<span class="sc">$</span>Rings)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb64-32"><a href="#cb64-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-33"><a href="#cb64-33" aria-hidden="true" tabindex="-1"></a>predictions_f <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_f, test_f)</span>
<span id="cb64-34"><a href="#cb64-34" aria-hidden="true" tabindex="-1"></a>rmse_f <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((predictions_f <span class="sc">-</span> test_f<span class="sc">$</span>Rings)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb64-35"><a href="#cb64-35" aria-hidden="true" tabindex="-1"></a>r2_f <span class="ot">&lt;-</span> <span class="fu">cor</span>(predictions_f, test_f<span class="sc">$</span>Rings)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb64-36"><a href="#cb64-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-37"><a href="#cb64-37" aria-hidden="true" tabindex="-1"></a>predictions_i <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_i, test_i)</span>
<span id="cb64-38"><a href="#cb64-38" aria-hidden="true" tabindex="-1"></a>rmse_i <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((predictions_i <span class="sc">-</span> test_i<span class="sc">$</span>Rings)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb64-39"><a href="#cb64-39" aria-hidden="true" tabindex="-1"></a>r2_i <span class="ot">&lt;-</span> <span class="fu">cor</span>(predictions_i, test_i<span class="sc">$</span>Rings)<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb64-40"><a href="#cb64-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-41"><a href="#cb64-41" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Male RMSE:"</span>, rmse_m, <span class="st">"R²:"</span>, r2_m, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Male RMSE: 1.938495 R²: 0.5603675 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Female RMSE:"</span>, rmse_f, <span class="st">"R²:"</span>, r2_f, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Female RMSE: 2.333701 R²: 0.4842709 </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Infant RMSE:"</span>, rmse_i, <span class="st">"R²:"</span>, r2_i, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Infant RMSE: 1.337307 R²: 0.7408071 </code></pre>
</div>
</div>
</section>
<section id="interpretation-5" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-5"><strong>Interpretation:</strong></h3>
<p>The models perform best for infant abalones, indicating that the features selected for prediction are more predictive for this group. In contrast, the models for male and especially female abalones show lower accuracy and fit, suggesting potential complexities or variations in growth patterns not as effectively captured by the model. This analysis highlights the need for potentially refining the models or exploring additional features that could better account for the variations in ring counts, particularly for female abalones.</p>
</section>
<section id="relation-between-rings-and-predictors" class="level3">
<h3 class="anchored" data-anchor-id="relation-between-rings-and-predictors"><strong>Relation between Rings and Predictors:</strong></h3>
<p>Predictor transformations are techniques used to modify the original predictor variables to enhance the performance and interpretability of models. These transformations are crucial for addressing issues such as non-linearity, non-normality, heteroscedasticity (non-constant variance), and to better capture the relationships between predictors and the response variable.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'gridExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:randomForest':

    combine</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    combine</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>indexes <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(abalone), <span class="at">size =</span> <span class="fl">0.3</span> <span class="sc">*</span> <span class="fu">nrow</span>(abalone))</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>abalone_train <span class="ot">&lt;-</span> abalone[<span class="sc">-</span>indexes,]</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>abalone_test <span class="ot">&lt;-</span> abalone[indexes,]</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">3</span>),<span class="at">oma=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>create_scatter_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(xvar,yvar,xtitle,ytitle) {</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(abalone_train,<span class="fu">aes</span>(<span class="at">x=</span>xvar,<span class="at">y=</span>yvar, <span class="at">col=</span>Sex)) <span class="sc">+</span> </span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_jitter</span>() <span class="sc">+</span> </span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="fu">paste</span>(xtitle)) <span class="sc">+</span>  </span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ylab</span>(<span class="fu">paste</span>(ytitle))</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(</span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a><span class="fu">create_scatter_plot</span>(abalone_train<span class="sc">$</span>Length,abalone_train<span class="sc">$</span>Rings,<span class="st">"Length"</span>,<span class="st">"Rings"</span>),</span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a><span class="fu">create_scatter_plot</span>(abalone_train<span class="sc">$</span>Diameter,abalone_train<span class="sc">$</span>Rings,<span class="st">"Diameter"</span>,<span class="st">"Rings"</span>),</span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a><span class="fu">create_scatter_plot</span>(abalone_train<span class="sc">$</span>Height,abalone_train<span class="sc">$</span>Rings,<span class="st">"Height"</span>,<span class="st">"Rings"</span>),</span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a><span class="fu">create_scatter_plot</span>(abalone_train<span class="sc">$</span>Whole_weight,abalone_train<span class="sc">$</span>Rings,<span class="st">"Whole_weight"</span>,<span class="st">"Rings"</span>),</span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a><span class="fu">create_scatter_plot</span>(abalone_train<span class="sc">$</span>Shell_weight,abalone_train<span class="sc">$</span>Rings,<span class="st">"Shell_weight"</span>,<span class="st">"Rings"</span>),</span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a><span class="fu">create_scatter_plot</span>(abalone_train<span class="sc">$</span>Shucked_weight,abalone_train<span class="sc">$</span>Rings,<span class="st">"Shucked_weight"</span>,<span class="st">"Rings"</span>),</span>
<span id="cb74-21"><a href="#cb74-21" aria-hidden="true" tabindex="-1"></a><span class="fu">create_scatter_plot</span>(abalone_train<span class="sc">$</span>Viscera_weight,abalone_train<span class="sc">$</span>Rings,<span class="st">"Viscera_weight"</span>,<span class="st">"Rings"</span>)</span>
<span id="cb74-22"><a href="#cb74-22" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Final_Project_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="interpretation-6" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-6"><strong>Interpretation:</strong></h3>
<p>The scatter plots provided display various physical measurements against the number of rings in abalones, categorized by sex. These plots suggest potential non-linear relationships and variable scales, indicating that transformations such as logarithmic, polynomial, or standardizing might enhance model accuracy by normalizing distributions and reducing skewness. The evident differences across sexes also hint that interactions between predictors and sex could be significant, potentially necessitating separate models or tailored transformations for each sex group. Implementing such transformations could address the non-linear patterns, manage the influence of outliers, and standardize predictor scales, thereby improving the interpretability and performance of predictive models for estimating abalone age.</p>
</section>
<section id="advantages" class="level3">
<h3 class="anchored" data-anchor-id="advantages"><strong>Advantages:</strong></h3>
<ol type="1">
<li><p><strong>Handling Non-Linearity</strong>: Random forests effectively manage non-linear relationships between variables without the need for transformations, making them ideal for complex ecological data like that of abalones.</p></li>
<li><p><strong>Feature Importance</strong>: This method provides valuable insights into which features (e.g., shell weight, diameter) are most predictive of age, aiding in understanding biological growth patterns.</p></li>
<li><p><strong>Robust to Overfitting</strong>: Due to the ensemble nature of random forests, where multiple trees vote on the outcome, the model is generally more robust to overfitting compared to single decision trees.</p></li>
<li><p><strong>Accommodating Missing Data</strong>: Random forests can handle missing values in the data without requiring explicit imputation, which can simplify preprocessing steps.</p></li>
<li><p><strong>Model Flexibility</strong>: They can be used for both classification and regression tasks, providing flexibility in terms of application.</p></li>
</ol>
</section>
<section id="disadvantages" class="level3">
<h3 class="anchored" data-anchor-id="disadvantages"><strong>Disadvantages:</strong></h3>
<ol type="1">
<li><p><strong>Model Complexity and Interpretability</strong>: Random forests involve numerous decision trees, which can make the model complex and difficult to interpret compared to simpler, linear models.</p></li>
<li><p><strong>Computationally Intensive</strong>: Training a random forest can be computationally expensive, especially with a large number of trees and deep tree structures.</p></li>
<li><p><strong>Less Effective for Extrapolation</strong>: They do not perform well in cases where predictions need to be made outside the range of the training data’s features.</p></li>
</ol>
</section>
<section id="limitations" class="level3">
<h3 class="anchored" data-anchor-id="limitations"><strong>Limitations:</strong></h3>
<ol type="1">
<li><p><strong>Hyperparameter Tuning</strong>: Determining the optimal number of trees, depth of each tree, and other parameters can be time-consuming and requires a methodical approach to tuning.</p></li>
<li><p><strong>Data Imbalance</strong>: If the dataset is imbalanced, random forest models can be biased towards the majority class, especially in classification tasks.</p></li>
<li><p><strong>High Dimensionality</strong>: While random forests handle multiple features well, extremely high-dimensional spaces (many features) can lead to longer training times and might require dimensionality reduction techniques to ensure model efficiency.</p></li>
<li><p><strong>No Performance Guarantee</strong>: As with any machine learning model, there is no guarantee that a random forest will perform well on all types of data, and its success heavily depends on the nature of the dataset and how representative the training data is of the broader population of abalones.</p></li>
</ol>
<p><strong>Conclusion:</strong></p>
<p>As a summary to the Research questions in report,</p>
<p>According to the analysis and interpretation when the physical measurements are high i.e., when the length, diameter and weight is a greater number then the age of the abalone is also older.Random Forest and Logistic Regression models were employed to predict abalone age, defined by the number of rings (age = rings + 1.5 years). Predictive models used physical measurements like shell length, diameter, and weight as inputs.</p>
<p>The age of abalone was predicted by comparing various different models such as SVM, GBM, random forest and Linear Regression, out of which Random forest gave the best accuracy of 97% after PCA data was used for the model.</p>
<p>Random Forest models were trained separately for male, female, and infant abalones. The results indicated differences in predictive accuracy.findings suggest significant differences in how well physical measurements can predict age across different sex categories. This could be due to intrinsic differences in growth patterns or the effectiveness of the used features in capturing underlying patterns for each category.Infant Abalones exhibited the best predictive accuracy with an RMSE of 1.765061 and an R² of 0.5488142, suggesting that age prediction is more straightforward or consistent in younger abalones, or the features used are more predictive for this group.</p>
<p><strong>References:</strong></p>
<p>[1] <em>UCI Machine Learning Repository</em>. (n.d.).&nbsp;https://archive.ics.uci.edu/dataset/1/abalone</p>
<p>[2] Allhan Uysal and Altay Guvenir. Instance-Based Regression by Partitioning Feature projections. Applied.2004.</p>
<p>[3] Lin, A., &amp; Meyers, M. A. (2005), Growth and structure in abalone shell. Materials Science and Engineering: A, 390(1-2), 27-41</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>